@extends('admin.layout')
@section('title', $product->exists ? __('marketplace.admin.products.edit_title') : __('marketplace.admin.products.new'))
@section('content')
<section class="market-admin"><header class="market-head"><div><span class="admin-eyebrow">MARKETPLACE</span><h1>{{ $product->exists ? __('marketplace.admin.products.edit_title') : __('marketplace.admin.products.new') }}</h1><p>{{ __('marketplace.admin.products.description') }}</p></div><a class="market-button is-light" href="{{ route('admin.marketplace.products.index') }}">← {{ __('marketplace.admin.common.back') }}</a></header>
<article class="market-card"><form class="market-form" method="post" enctype="multipart/form-data" action="{{ $product->exists ? route('admin.marketplace.products.update', $product) : route('admin.marketplace.products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<label>{{ __('marketplace.admin.products.category') }}<select name="marketplace_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)old('marketplace_category_id', $product->marketplace_category_id) === $category->id)>{{ $category->name }}</option>@endforeach</select></label>
<label>{{ __('marketplace.admin.products.name') }}<input name="name" required value="{{ old('name', $product->name) }}"></label><label>{{ __('marketplace.admin.products.slug') }}<input name="slug" value="{{ old('slug', $product->slug) }}"></label><label>{{ __('marketplace.admin.products.short_description') }}<textarea name="short_description" maxlength="500" required>{{ old('short_description', $product->short_description) }}</textarea></label><label>{{ __('marketplace.admin.products.description_field') }}<textarea name="description" required>{{ old('description', $product->description) }}</textarea></label>
<label>{{ __('marketplace.admin.products.image') }}<input type="file" name="image" accept="image/jpeg,image/png,image/webp"><small>{{ __('marketplace.admin.products.image_help') }}</small>@if($product->imageUrl())<img class="market-thumb" src="{{ $product->imageUrl() }}" alt="">@endif</label>
<label>{{ __('marketplace.admin.products.print_size') }}<select name="print_size" required>@foreach($printSizes as $size)<option @selected(old('print_size', $product->print_size) === $size)>{{ $size }}</option>@endforeach</select></label><label>{{ __('marketplace.admin.products.token_cost') }}<input type="number" min="1" name="token_cost" required value="{{ old('token_cost', $product->token_cost) }}"></label><label>{{ __('marketplace.admin.products.sort_order') }}<input type="number" min="0" name="sort_order" value="{{ old('sort_order', $product->sort_order ?? 0) }}"></label><label class="market-check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->is_active))>{{ __('marketplace.admin.common.active') }}</label><button class="market-button">{{ __('marketplace.admin.common.save') }}</button></form></article></section>
@endsection
