@extends('admin.layout')
@section('title', $provider->exists ? __('marketplace.admin.providers.edit_title') : __('marketplace.admin.providers.new'))
@section('content')
<section class="market-admin"><header class="market-head"><div><span class="admin-eyebrow">MARKETPLACE</span><h1>{{ $provider->exists ? __('marketplace.admin.providers.edit_title') : __('marketplace.admin.providers.new') }}</h1><p>{{ __('marketplace.admin.providers.description') }}</p></div><a class="market-button is-light" href="{{ route('admin.marketplace.providers.index') }}">← {{ __('marketplace.admin.common.back') }}</a></header>
<article class="market-card"><form class="market-form" method="post" action="{{ $provider->exists ? route('admin.marketplace.providers.update', $provider) : route('admin.marketplace.providers.store') }}">@csrf @if($provider->exists) @method('PUT') @endif<label>{{ __('marketplace.admin.providers.name') }}<input name="name" required value="{{ old('name', $provider->name) }}"></label><label>{{ __('marketplace.admin.providers.notes') }}<textarea name="notes">{{ old('notes', $provider->notes) }}</textarea></label><label class="market-check"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $provider->is_active))>{{ __('marketplace.admin.common.active') }}</label>
<h2>{{ __('marketplace.admin.providers.rates') }}</h2><div id="market-rates">@php($rates = old('rates', $provider->exists ? $provider->rates->toArray() : [['country_code' => 'PL', 'print_size' => '', 'token_cost' => 8]]))@foreach($rates as $index => $rate)<div class="market-rate"><label>{{ __('marketplace.admin.providers.country') }}<input name="rates[{{ $index }}][country_code]" maxlength="2" value="{{ $rate['country_code'] ?? '' }}"><small>{{ __('marketplace.admin.providers.country_help') }}</small></label><label>{{ __('marketplace.admin.providers.format') }}<select name="rates[{{ $index }}][print_size]"><option value="">{{ __('marketplace.admin.providers.all_formats') }}</option>@foreach($printSizes as $size)<option @selected(($rate['print_size'] ?? '') === $size)>{{ $size }}</option>@endforeach</select></label><label>{{ __('marketplace.admin.providers.token_cost') }}<input type="number" min="0" required name="rates[{{ $index }}][token_cost]" value="{{ $rate['token_cost'] ?? 0 }}"></label><button class="market-button is-danger" type="button" data-remove-rate>×</button></div>@endforeach</div><button class="market-button is-light" type="button" id="add-market-rate">+ {{ __('marketplace.admin.providers.add_rate') }}</button><button class="market-button">{{ __('marketplace.admin.common.save') }}</button></form></article></section>
<template id="market-rate-template"><div class="market-rate"><label>{{ __('marketplace.admin.providers.country') }}<input data-name="country_code" maxlength="2"><small>{{ __('marketplace.admin.providers.country_help') }}</small></label><label>{{ __('marketplace.admin.providers.format') }}<select data-name="print_size"><option value="">{{ __('marketplace.admin.providers.all_formats') }}</option>@foreach($printSizes as $size)<option>{{ $size }}</option>@endforeach</select></label><label>{{ __('marketplace.admin.providers.token_cost') }}<input data-name="token_cost" type="number" min="0" required value="0"></label><button class="market-button is-danger" type="button" data-remove-rate>×</button></div></template>
<script>document.addEventListener('DOMContentLoaded',()=>{const box=document.querySelector('#market-rates'),tpl=document.querySelector('#market-rate-template'),add=document.querySelector('#add-market-rate');const bind=()=>document.querySelectorAll('[data-remove-rate]').forEach(button=>button.onclick=()=>{if(box.children.length>1)button.closest('.market-rate').remove()});add.onclick=()=>{const index=box.children.length,row=tpl.content.firstElementChild.cloneNode(true);row.querySelectorAll('[data-name]').forEach(input=>input.name=`rates[${index}][${input.dataset.name}]`);box.append(row);bind()};bind()})</script>
@endsection
