@extends('layouts.app')
@section('title', __('lenticular_studio.single_form.title').' — '.__('site.title'))
@push('head')@vite(['resources/css/lab.css', 'resources/css/lenticular-studio.css', 'resources/css/lenticular-ai-pair.css', 'resources/js/lenticular-studio.js'])@endpush
@section('content')
<section class="studio-page"><div class="site-container studio-form-shell">
    <nav class="lab-breadcrumbs"><a href="{{ route('lab.lenticular.studio', ['locale' => app()->getLocale()]) }}">AI LENTICULAR STUDIO</a><span>›</span><span>{{ __('lenticular_studio.paths.single.title') }}</span></nav>
    <header class="studio-form-heading"><span class="lab-kicker">{{ __('lenticular_studio.single_form.kicker') }}</span><h1>{{ __('lenticular_studio.single_form.title') }}</h1><p>{{ __('lenticular_studio.single_form.description') }}</p></header>
    <form method="post" enctype="multipart/form-data" action="{{ route('lab.lenticular.ai.single.store', ['locale' => app()->getLocale()]) }}" class="studio-ai-form">@csrf
        <section class="studio-form-card"><div class="studio-form-card-title"><span>1</span><div><h2>{{ __('lenticular_studio.pair_form.project_title') }}</h2><p>{{ __('lenticular_studio.pair_form.project_help') }}</p></div></div><label class="studio-field"><span>{{ __('lenticular_projects.name') }}</span><input name="name" value="{{ old('name') }}" maxlength="150" required></label></section>
        <section class="studio-form-card"><div class="studio-form-card-title"><span>2</span><div><h2>{{ __('lenticular_studio.single_form.image_title') }}</h2><p>{{ __('lenticular_studio.single_form.image_help') }}</p></div></div><div class="studio-upload-grid studio-upload-grid-single"><label class="studio-image-upload"><input type="file" name="source_image" accept="image/jpeg,image/png,image/webp" required data-studio-image-input><span class="studio-upload-symbol">◉</span><strong>{{ __('lenticular_studio.single_form.source_image') }}</strong><small>{{ __('lenticular_studio.pair_form.image_limit') }}</small><img alt="" hidden data-studio-image-preview></label></div></section>
        <section class="studio-form-card"><div class="studio-form-card-title"><span>3</span><div><h2>{{ __('lenticular_studio.pair_form.print_title') }}</h2><p>{{ __('lenticular_studio.pair_form.print_help') }}</p></div></div><div class="studio-options-grid studio-options-grid-print"><fieldset><legend>{{ __('lenticular_projects.print_size') }}</legend><div class="lenticular-choice-row">@foreach($printSizes as $size)<label><input type="radio" name="print_size" value="{{ $size }}" @checked(old('print_size','A4')===$size)> {{ $size }}</label>@endforeach</div></fieldset><label class="studio-field"><span>{{ __('lenticular_projects.printer_dpi') }}</span><select name="printer_dpi" required>@foreach($printerDpis as $dpi)<option value="{{ $dpi }}" @selected((int)old('printer_dpi',1200)===$dpi)>{{ $dpi }} DPI</option>@endforeach</select></label><fieldset><legend>{{ __('lenticular_projects.lens_lpi') }}</legend><div class="lenticular-choice-row">@foreach([50,60,75] as $lpi)<label><input type="radio" name="lpi" value="{{ $lpi }}" @checked((int)old('lpi',60)===$lpi)> {{ $lpi }} LPI</label>@endforeach</div></fieldset></div></section>
        <section class="studio-form-card studio-confirm-card"><div><span class="lab-kicker">{{ __('lenticular_studio.pair_form.ready_kicker') }}</span><h2>{{ __('lenticular_studio.single_form.ready_title') }}</h2></div><button class="lab-primary-button" type="submit" @disabled(!$settings->configured() || !$agentReady)>{{ __('lenticular_studio.single_form.generate') }}</button></section>
    </form>
</div></section>
@endsection
