@extends('layouts.app')
@section('title', __('lenticular_studio.sequence_form.title').' — '.__('site.title'))
@push('head')@vite(['resources/css/lab.css', 'resources/css/lenticular-studio.css', 'resources/css/lenticular-ai-pair.css', 'resources/js/lenticular-studio.js'])@endpush
@section('content')
<section class="studio-page"><div class="site-container studio-form-shell">
    <nav class="lab-breadcrumbs"><a href="{{ route('lab.lenticular.studio', ['locale' => app()->getLocale()]) }}">AI LENTICULAR STUDIO</a><span>›</span><span>{{ __('lenticular_studio.paths.sequence.title') }}</span></nav>
    <header class="studio-form-heading"><span class="lab-kicker">{{ __('lenticular_studio.sequence_form.kicker') }}</span><h1>{{ __('lenticular_studio.sequence_form.title') }}</h1><p>{{ __('lenticular_studio.sequence_form.description') }}</p></header>
    <form method="post" enctype="multipart/form-data" action="{{ route('lab.lenticular.ai.sequence.store', ['locale' => app()->getLocale()]) }}" class="studio-ai-form" data-sequence-form>@csrf
        <section class="studio-form-card"><div class="studio-form-card-title"><span>1</span><div><h2>{{ __('lenticular_studio.pair_form.project_title') }}</h2><p>{{ __('lenticular_studio.pair_form.project_help') }}</p></div></div><label class="studio-field"><span>{{ __('lenticular_projects.name') }}</span><input name="name" value="{{ old('name') }}" maxlength="150" required></label></section>
        <section class="studio-form-card"><div class="studio-form-card-title"><span>2</span><div><h2>{{ __('lenticular_studio.sequence_form.images_title') }}</h2><p>{{ __('lenticular_studio.sequence_form.images_help', ['limit' => $planLimit]) }}</p></div></div><label class="studio-image-upload studio-sequence-upload"><input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple required data-sequence-input><span class="studio-upload-symbol">▥</span><strong>{{ __('lenticular_studio.sequence_form.choose_images') }}</strong><small>{{ __('lenticular_studio.sequence_form.image_limit') }}</small></label><div class="studio-sequence-preview" data-sequence-preview></div><label class="studio-confirm"><input type="checkbox" name="reverse" value="1"><span>{{ __('lenticular_studio.sequence_form.reverse') }}</span></label></section>
        <section class="studio-form-card"><div class="studio-form-card-title"><span>3</span><div><h2>{{ __('lenticular_studio.pair_form.print_title') }}</h2><p>{{ __('lenticular_studio.sequence_form.print_help') }}</p></div></div><div class="studio-options-grid studio-options-grid-print"><fieldset><legend>{{ __('lenticular_projects.print_size') }}</legend><div class="lenticular-choice-row">@foreach($printSizes as $size)<label><input type="radio" name="print_size" value="{{ $size }}" @checked(old('print_size', $premium ? 'A4' : 'A5')===$size)> {{ $size }}</label>@endforeach</div></fieldset><label class="studio-field"><span>{{ __('lenticular_studio.sequence_form.printer_dpi') }}</span><select name="printer_dpi" required>@foreach($printerDpis as $dpi)<option value="{{ $dpi }}" @selected((int)old('printer_dpi',1200)===$dpi)>{{ $dpi }} DPI</option>@endforeach</select></label><fieldset><legend>{{ __('lenticular_projects.lens_lpi') }}</legend><div class="lenticular-choice-row">@foreach([50,60,75] as $lpi)<label><input type="radio" name="lpi" value="{{ $lpi }}" @checked((int)old('lpi',60)===$lpi)> {{ $lpi }} LPI</label>@endforeach</div></fieldset></div><p class="studio-sequence-count" data-sequence-count data-count-template="{{ __('lenticular_studio.sequence_form.selected', ['count' => ':count']) }}"></p><button class="lab-primary-button" type="submit">{{ __('lenticular_studio.sequence_form.continue') }} →</button></section>
    </form>
</div></section>
@endsection
